Sources/Pathos/readWrite.swift, Tests/LinuxMain.swift, Tests/PathosTests/ReadingTests.swift
Append `0` before converting from bytes to string. Hardcode empty content when
reading from directory.
=> Fix reading tests on Linux

.gitignore, Makefile, README.md, Resources/Info.plist, Resources/release.xcconfig, project.yml
1. Use [XcodeGen][1] to generate a Xcode project. Note that SwiftPM is not good
enough since we need a Info.plist and various configurations (via .xcconfig).
2. Use Carthage's `build --archive` command to create the framework archive
to go alone with releases.
3. Both tools binary is checked-in in `bin`.
[1]: https://github.com/yonaskolb/XcodeGen
=> Add Carthage support

Makefile, Sources/Pathos/temporary.swift, Tests/PathosTests/DefaultTemporaryDirectorySearchingTests.swift, Tests/PathosTests/DefaultTemporaryDirectoryTests.swift, Tests/PathosTests/XCTestManifests.swift
Copied behavior from Python with a different public interface design.
Instead of asking user to set the path to `nil` to reset to default
value, expose the function that calculate the default value so users can
use it to reset (or whatever).
=> Implement default temprary root

Makefile
The problem with embedded binary is it goes out-of-date. Asking CI and
developer/packager to have it installed is a reasonable sacrifice.
=> Use Carthage of the internet

Makefile
A make target rename cause carthage build tests to fail.
=> Fix carthage tests

Sources/Pathos/FilePermission.swift, Sources/Pathos/PathRepresentable.swift, Sources/Pathos/PathosError.swift, Sources/Pathos/children.swift, Sources/Pathos/temporary.swift
Use Xcode's default format because it's most contributor friendly.
=> Unify docstring format

Sources/Pathos/children.swift
Blame `scandir`. But package it in a implementation-detail-is-hidden
kind of way.
=> Document errors for children

Sources/Pathos/currentWorkingDirectory.swift, Sources/Pathos/glob.swift, Sources/Pathos/temporary.swift
These should stay static since they are not relavent to the specific
instance.
=> Remove non-instance-specific methods

Sources/Pathos/children.swift, Tests/PathosTests/ChildrenTests.swift
When recursing into relative paths, child directory is joint with parent
twice. That leads to system error complaining about non-existing
directories. Fix this bug, add test for regression.
=> Fix children bug

Sources/Pathos/glob.swift
No need to force unwrap here. (even tho there's a range check)
=> Remove force-unwrap

Sources/Pathos/pathAnalysis.swift, Tests/PathosTests/CommonPathTests.swift, Tests/PathosTests/XCTestManifests.swift
Implementation, docstring and tests for commonPath. Tests are taken from
Python.
=> Implement commonPath

Sources/Pathos/constants.swift, Sources/Pathos/helpers.swift, Sources/Pathos/pathAnalysis.swift, Sources/Pathos/pathAnalysisWithIO.swift, Tests/PathosTests/RelativePathInferringCurrentDirectoryTests.swift, Tests/PathosTests/RelativePathTests.swift, Tests/PathosTests/XCTestManifests.swift
There are 2 variants:
Variant 1 is a pure computation that doesn't involve IO.
Variant 2 requires `getcwd` which could throw an error.
Implement, document, test.
=> Implement relativePath

Sources/Pathos/children.swift, Sources/Pathos/pathAnalysis.swift, Sources/Pathos/pathAnalysisWithIO.swift, Sources/Pathos/temporary.swift, Tests/PathosTests/DefaultTemporaryDirectorySearchingTests.swift, Tests/PathosTests/FixtureSupport.swift, Tests/PathosTests/JoinPathTests.swift, Tests/PathosTests/MakeDirectoryTests.swift, Tests/PathosTests/RelativePathInferringCurrentDirectoryTests.swift, Tests/PathosTests/XCTestManifests.swift
Clean up public interfaces so there are two versions left:
* a version that provides both type safety with signature guanrenteeing
at least 2 arguments are provided
* a version that takes an array of paths and tolerates zero arguments
And mirror these in PathRepresentable, of course.
Close #50
=> Update path-joining interfaces

Makefile
In the case where update is interupted, this file will be removed but
not updated.
=> Touch Linux test manifests before updating

Sources/Pathos/currentWorkingDirectory.swift, Tests/PathosTests/CurrentWorkingDirectoryTests.swift, Tests/PathosTests/XCTestManifests.swift
Add APIs for executing block in a temporarily changed working directory. These proved to be super handy in practice.
=> Add working directory execution

Sources/Pathos/readWrite.swift, Sources/Pathos/temporary.swift, Tests/PathosTests/MoveTests.swift, Tests/PathosTests/WritingTests.swift
1. content comes first. Move away from the faux OOP mindset.
2. omit needless words. String, for example, **was** repeating the type
information here.
=> Rename write API

Sources/Pathos/pathAnalysisWithIO.swift, Sources/Pathos/temporary.swift, Tests/PathosTests/MakeAbsoluteTests.swift
This way it's less misleading. `make` suggests actual modification of
the file system.
=> Rename makeAbsolute to absolutePath

Sources/Pathos/permissions.swift, Tests/PathosTests/PermissionsTests.swift
The permissions APIs has aligned with the preposition `for` when
mentioning "path."
=> Rename add permission paramater

Sources/Pathos/pathAnalysis.swift, Tests/PathosTests/JoinPathTests.swift
Use `+` for joining `PathRepresentable`s.
=> Add syntax sugar for joining paths

Sources/Pathos/readWrite.swift
The byte count when converting a Swift string to C string includes the null
terminator. We don't want to write it with `pwrite`.
=> Fix writing bug

Sources/Pathos/temporary.swift
Because a user may be interested in that information.
Closes #110
=> Add error for OO withTemporaryDirectory

CHANGELOG.md, Sources/Pathos/children.swift
This removes a warning from Swift 5.2
=> Use better Swift API for reading dirent field

CHANGELOG.md, Sources/Pathos/permissions.swift, Tests/PathosTests/PermissionsTests.swift, Tests/PathosTests/XCTestManifests.swift
Remove adding/removing permissions in favor of directly setting it.
Deprecated the following:
- `add(_:forPath:)`
- `remove(_:forPath:)`
- `PathRepresentable.add(_:)`
- `PathRepresentable.remove(_:)`
=> Deprecate some permission APIs

CHANGELOG.md, Sources/Pathos/attributes.swift, Sources/Pathos/copy.swift, Sources/Pathos/permissions.swift, Tests/PathosTests/CopyFileTests.swift, Tests/PathosTests/ExistsTests.swift
"symlink" should be a well understood term for users of this library.
Previous attemts to "English" the API is dubious at best.
However, due to the fact that these changes happens at arugment label
level, all of which came with default values, we can not properly
deprecate the old function names without introducing ambiguities at
user's callsite. So these will have to be breaking changes.
Closes #131
=> Improve consistency when refers to symlinks

Sources/Pathos/copy.swift, Sources/Pathos/readWrite.swift
These are correctly diagnosed as not mutated by Xcode 12, this change is
backwards compatible.
=> Fix mutability warnings

Sources/Pathos/Windows/Path+Windows.swift
The crazy move-before-deletion thing does not need to happen if the
deletion is non-recursive
=> Fix non-recursive Path.delete on Windows

Sources/Pathos/BinaryString.swift, Sources/Pathos/POSIX/Path+Darwin.swift, Sources/Pathos/POSIX/Path+Glibc.swift, Sources/Pathos/POSIX/Path+POSIX.swift, Sources/Pathos/Windows/Path+Windows.swift
`BinaryString.cString` previously returns an unscoped pointer to its storage, which is against recommendation of Swift's documentation. Fix it by exposing the pointer to a scope.
=> Fix cString pointer lifetime

CHANGELOG.md, Sources/Pathos/children.swift
Following symlink shouldn't imply recursive
=> Fix recursive children

Sources/Pathos/Path.swift, Tests/PathosTests/ChildrenTests.swift, Tests/PathosTests/CopyTests.swift, Tests/PathosTests/GlobTests.swift, Tests/PathosTests/MetadataTests.swift, Tests/PathosTests/RealTests.swift, Tests/PathosTests/SymlinkTests.swift, Tests/PathosTests/WriteTests.swift
Make it explicit what we are writing.
Closes #263.
=> Add `utf8` to Path.write

Sources/Pathos/POSIX/PurePOSIXPath.swift, Sources/Pathos/Path.swift, Sources/Pathos/Windows/PureWindowsPath.swift
Two `Path.init...`s take a `String`. So it would be ambiguous in code
like `someArrayOfString.map(Path.init)`. So one of them has to go.
=> Resolve ambiguity
