Sources/Pathos/SystemError.swift
Sources/Pathos/manipulate.swift
TODO.md

Partially stolen from Python stdlib.

Implement recursive makeDirectory

---

Sources/Pathos/manipulate.swift
Tests/PathosTests/MakeDirectoryTests.swift

Make directory tests

---

Sources/Pathos/pathAnalysisWithIO.swift

Remove force unwrap

---

Sources/Pathos/helpers.swift

The charactor to be stripped was hard-coded. Oops.

Fix _stripFromRight

---

Tests/PathosTests/FixtureSupport.swift

These will be used in future tests

Add more fixtures

---

Tests/PathosTests/XCTestManifests.swift

Update Linux test manifest

---

Sources/Pathos/glob.swift

And include a `*` in top-level glob for directories.

Document glob

---

Sources/Pathos/pathAnalysisWithIO.swift
Tests/PathosTests/RealPathTests.swift
Tests/PathosTests/XCTestManifests.swift

Implement real path, add docstring, and tests.

Implement realPath

---

Sources/Pathos/symbolicLink.swift
Tests/PathosTests/MakeSymbolicLinkTests.swift
Tests/PathosTests/XCTestManifests.swift

Add tests for make symbolic links

---

Sources/Pathos/permissions.swift
Tests/PathosTests/PermissionsTests.swift
Tests/PathosTests/XCTestManifests.swift

Add functions to add/remove permissions.
Add unit tests to everything.
Add docstring for everything.

Update permissions APIs

---

Sources/Pathos/currentWorkingDirectory.swift
Tests/PathosTests/ChildrenTests.swift
Tests/PathosTests/CopyFileTests.swift
Tests/PathosTests/CurrentWorkingDirectoryTests.swift
Tests/PathosTests/GlobTests.swift
Tests/PathosTests/MakeSymbolicLinkTests.swift
Tests/PathosTests/RelativePathInferringCurrentDirectoryTests.swift
Tests/PathosTests/WritingTests.swift
Tests/PathosTests/XCTestManifests.swift

Add tests, rename setter, add docstrings.

Update current working directory implementation

---

Sources/Pathos/attributes.swift
Sources/Pathos/temporary.swift
Tests/PathosTests/TemporaryDirectoryTests.swift
Tests/PathosTests/XCTestManifests.swift

XCTest is not final, who would've thought eh?

Fix temporary tests

---

Sources/Pathos/temporary.swift
Tests/PathosTests/TemporaryFileTests.swift
Tests/PathosTests/XCTestManifests.swift

XCTest is not the same as XCTestCase

Fix tests for temporary files

---

Sources/Pathos/temporary.swift
Tests/PathosTests/TemporaryDirectoryTests.swift
Tests/PathosTests/XCTestManifests.swift

Add API for auto transition, auto deleted temporary directory.

Add automatically deleted temporary directory

---

Sources/Pathos/manipulate.swift
Sources/Pathos/temporary.swift
Tests/PathosTests/DefaultTemporaryDirectoryTests.swift
Tests/PathosTests/MoveTests.swift
Tests/PathosTests/XCTestManifests.swift

Unit tests and docstring for movePath.

Add docstring and tests for movePath

---

Sources/Pathos/manipulate.swift
Sources/Pathos/readWrite.swift
Sources/Pathos/temporary.swift

More things to consider before we are done.

Add some TODOs

---

Sources/Pathos/manipulate.swift
Tests/PathosTests/DeleteTests.swift
Tests/PathosTests/XCTestManifests.swift

Also switch to sensible default for recursive deletion.

Add tests for deletePath

---

Sources/Pathos/copy.swift
Sources/Pathos/manipulate.swift
Sources/Pathos/symbolicLink.swift
Sources/Pathos/temporary.swift
Tests/PathosTests/CurrentWorkingDirectoryTests.swift
Tests/PathosTests/DeleteTests.swift
Tests/PathosTests/FixtureSupport.swift
Tests/PathosTests/MakeDirectoryTests.swift
Tests/PathosTests/MakeSymbolicLinkTests.swift
Tests/PathosTests/MoveTests.swift
Tests/PathosTests/PermissionsTests.swift
Tests/PathosTests/RelativePathInferringCurrentDirectoryTests.swift
Tests/PathosTests/TemporaryDirectoryTests.swift
Tests/PathosTests/TemporaryFileTests.swift

Eliminate "make" from symbols

---

Sources/Pathos/constants.swift
Sources/Pathos/glob.swift
Sources/Pathos/pathAnalysis.swift
Sources/Pathos/pathAnalysisWithIO.swift

Will be useful when Windows support is a thing.

Make separator public

---

README.md

This version of example shows off more functionalities.

Enhance README overview

---

Sources/Pathos/permissions.swift
Tests/PathosTests/PermissionsTests.swift

Unify permission preposition

---

Sources/Pathos/pathAnalysisWithIO.swift
Tests/PathosTests/ExpandUserDirectoryTests.swift
Tests/PathosTests/MakeAbsoluteTests.swift
Tests/PathosTests/RelativePathInferringCurrentDirectoryTests.swift

These new interfaces feels more natural

Rename some PathRepresentable properties

---

Sources/Pathos/copy.swift
Sources/Pathos/manipulate.swift
Sources/Pathos/symbolicLink.swift

Make side-effectful PathRepresentable methods' result discardable

Mark discardable results

---

Sources/Pathos/Path.swift
Tests/PathosTests/JoinPathTests.swift

All the automatic `able`s. ohmy.

Make Path *able

---

Sources/Pathos/children.swift

The implementation of these two were swapped 😭

Fix FIFO and UNKNOWN file identification

---

Sources/Pathos/children.swift

On macOS 10.15.4, accessing data structure returned by `scandir`
occassionally returns a mysterious `SIGSEGV (Address boundary error)`.
Replace it with opendir/readdir/closedir instead to mitigate this
problem.
Closes #122

Re-implement children(inPath:recursive)

---

Makefile

Update manual docker testing to 5.2

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
Makefile
README.md
RELEASING.md

This dramatically improved CI time.

Drop Carthage support

---

Sources/Pathos/Windows/Path+Windows.swift

Close file handles

---

Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Path.swift
Sources/Pathos/Windows/Path+Windows.swift
Tests/PathosTests/WorkingDirectoryTests.swift
Tests/PathosTests/XCTestManifests.swift

1. setting
2. temporary setting

Implement more current working directory stuff

---

Examples/CMakeLists.txt
Examples/mkdir/main.swift
Package.swift
Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/SystemError.swift
Sources/Pathos/Windows/Path+Windows.swift

Implement Path.makeDirectory

---

Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Windows/Path+Windows.swift

Implement Path.move

---

Sources/Pathos/BinaryString.swift
Sources/Pathos/POSIX/Path+Darwin.swift
Sources/Pathos/POSIX/Path+Glibc.swift
Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/POSIX/PathParts+POSIX.swift
Sources/Pathos/POSIX/PurePOSIXPath.swift
Sources/Pathos/Windows/Path+Windows.swift
Sources/Pathos/Windows/PathParts+Windows.swift
Tests/PathosTests/POSIXPathInitializationTests.swift

Make binary string faster

---

Sources/Pathos/Windows/Path+Windows.swift

Guarantee writable temp directory for windows Path.delete()

---

CMakeLists.txt
Package.swift
Scripts/Package_windows.swift
Scripts/cmake_root/Sources/Pathos/CMakeLists.txt
Scripts/cmake_root/Tests/CMakeLists.txt
Sources/CMakeLists.txt
Sources/Pathos/CMakeLists.txt
Sources/Pathos/Constants.swift
Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Windows/Path+Windows.swift
Sources/WindowsHelpers/CMakeLists.txt
Sources/WindowsHelpers/include/WindowsHelpers.h
Sources/WindowsHelpers/include/module.modulemap
Sources/WindowsHelpers/include/reparsedata.h
Tests/CMakeLists.txt
cmake/modules/CMakeLists.txt
cmake/modules/SwiftSupport.cmake

Implement Path.readSymlink()

---

Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Windows/Path+Windows.swift

Implement Path.makeSymlink(at:)

---

Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Windows/Path+Windows.swift
Tests/PathosTests/WriteTests.swift

Implement readBytes

---

Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Path.swift
Sources/Pathos/Windows/Path+Windows.swift

Rename write implementation

---

Examples/ls/main.swift
Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Windows/Path+Windows.swift

Make .children return type of each child

---

Sources/Pathos/BinaryString.swift
Sources/Pathos/POSIX/Path+POSIX.swift
Sources/Pathos/Path.swift
Sources/Pathos/PathParts.swift
Sources/Pathos/Windows/Metadata+Windows.swift
Sources/Pathos/Windows/Path+Windows.swift
Sources/Pathos/Windows/PureWindowsPath.swift
Sources/Pathos/Windows/WindowsFileType.swift
Tests/PathosTests/ChildrenTests.swift
Tests/PathosTests/POSIXPartsParsingTests.swift
Tests/PathosTests/WindowsPartsParsingTests.swift
Tests/PathosTests/XCTestManifests.swift

Add followSymlink option to .children()

---

Documentation/APIReference.md
Sources/Pathos/Path+Temporary.swift
Sources/Pathos/Path.swift

Make run-an-action label consistent

---

Sources/Pathos/POSIX/PurePOSIXPath.swift
Sources/Pathos/Path.swift
Sources/Pathos/PurePathRepresentable.swift
Sources/Pathos/Windows/PureWindowsPath.swift

Delete parse() from public interface

---

Sources/Pathos/SystemError.swift

Specifically: the Windows ones ;)

Steal error codes from System
